hepsi: derle calistir

derle:
	
	g++ -I ./include/ -o ./lib/Dugum.o -c ./src/Dugum.cpp
	g++ -I ./include/ -o ./lib/Yonetim.o -c ./src/Yonetim.cpp
	g++ -I ./include/ -o ./bin/Test ./lib/Dugum.o ./lib/Yonetim.o ./src/Test.cpp
calistir:
	./bin/Test